# Generated by Django 5.2.5 on 2025-08-18 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
